### ISSUE TITLE
빌드 실패

### ISSUE THREAD

**Issue by haeramkeem** [k-hackathon2022/Elon-kiosk-WebApp#1]
## Steps to reproduce the issue

- `npm install` 실행
- `npm run build` 실행

## Expected result

- 빌드 성공

## Resulted output

<img width="1440" alt="Screen Shot 2022-08-24 at 5 35 14 PM" src="https://user-images.githubusercontent.com/77822629/186371109-738f24fd-e85c-4ffc-9eaf-27a452713a32.png">

**Comment by chopinballadeno4** [comment]
error now course me
but it can run
